ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
fps = 60
HEALTH = 100
MONEY = 650

#enemy constants
SPAWN_COOLDOWN = 400

#turret constants
TURRET_LEVEL = 4
BUY_COST = 200
UPGRADE_COST = 100
KIL_REWARD = 1
ANIMATIONS_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5
